CREATE TABLE IF NOT EXISTS public.videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  category TEXT DEFAULT '',
  tags TEXT DEFAULT '',
  source_type TEXT NOT NULL DEFAULT 'google_drive',
  video_path TEXT NOT NULL,
  thumbnail_path TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  views INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT videos_source_type_check
    CHECK (source_type IN ('local', 'google_drive', 'youtube'))
);

CREATE INDEX IF NOT EXISTS videos_category_idx ON public.videos (category);
CREATE INDEX IF NOT EXISTS videos_created_at_idx ON public.videos (created_at DESC);
